import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect } from 'react'


export default function Home() {

  useEffect(() => {
   console.log('index page did mount');
  }, [])



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul>
          <li>
            <Link href="/About">
              <a>About us</a>
            </Link>
          </li>
          <li>
            <Link href='/Terms'>
              <a>
                Terms of Use
              </a>
            </Link>
          </li>
        </ul>
      </div>
    </div>
  )
}
